/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.colesenrollmentsystem;

import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 * SelectSchoolYear - AI Training and Prediction Form
 * @author Arch Coles
 */
public class SelectSchoolYear extends javax.swing.JFrame {
    
    private Training trainingModule;
    private Predict predictModule;

    /**
     * Creates new form SelectSchoolYear
     */
    public SelectSchoolYear() {
        initComponents();
        loadDatabases();
    }
    
    /**
     * Load available databases from the system
     */
    private void loadDatabases() {
        try {
            selectschoolyearcombobox.removeAllItems();
            ResultSet rs = ColesEnrollmentSystem.st.executeQuery("SHOW DATABASES;");
            while (rs.next()) {
                String db = rs.getString(1);
                if (!(db.equalsIgnoreCase("mysql")
                        || db.equalsIgnoreCase("performance_schema")
                        || db.equalsIgnoreCase("information_schema")
                        || db.equalsIgnoreCase("sys"))) {
                    selectschoolyearcombobox.addItem(db);
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error loading databases: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        selectschoolyearcombobox = new javax.swing.JComboBox<>();
        Selectschoolyearbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("SELECT SCHOOL YEAR TRAINING DATA");

        jLabel2.setText("SCHOOL YEAR");

        selectschoolyearcombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "school year" }));
        selectschoolyearcombobox.setToolTipText("");

        Selectschoolyearbutton.setText("SELECT");
        Selectschoolyearbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectschoolyearbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(37, 37, 37)
                                .addComponent(selectschoolyearcombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(Selectschoolyearbutton)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(selectschoolyearcombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(Selectschoolyearbutton)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SelectschoolyearbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectschoolyearbuttonActionPerformed
        String selectedDB = (String) selectschoolyearcombobox.getSelectedItem();
        if (selectedDB == null || selectedDB.isEmpty() || selectedDB.equals("school year")) {
            JOptionPane.showMessageDialog(this, "Please select a database");
            return;
        }
        
        // Set the selected database
        ColesEnrollmentSystem.db = selectedDB;
        
        // Train AI Model
        trainAIModel(selectedDB);
    }
    
    /**
     * Train AI model on selected database
     */
    private void trainAIModel(String selectedDB) {
        new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    JOptionPane.showMessageDialog(SelectSchoolYear.this, 
                        "Starting AI training on database: " + selectedDB + "\nThis may take a moment...",
                        "Training Started", JOptionPane.INFORMATION_MESSAGE);
                    
                    trainingModule = new Training(selectedDB);
                    
                    // Collect data
                    trainingModule.collectEnrollmentData();
                    int records = trainingModule.getTrainingData().numInstances();
                    
                    // Train classifier
                    trainingModule.trainClassifier();
                    
                    // Save model and ARFF file
                    trainingModule.saveModel();
                    
                    JOptionPane.showMessageDialog(SelectSchoolYear.this,
                        "Training Completed Successfully!\n\n" +
                        "Database: " + selectedDB + "\n" +
                        "Records Used: " + records + "\n" +
                        "Files Generated:\n" +
                        "  • " + selectedDB + "_enrollment.arff\n" +
                        "  • " + selectedDB + "_enrollment_model.model\n\n" +
                        "You can now use AI ENROLL to assign subjects to students!",
                        "Training Complete", JOptionPane.INFORMATION_MESSAGE);
                    
                    // Close this form after training
                    SelectSchoolYear.this.dispose();
                    
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(SelectSchoolYear.this,
                        "Error during training: " + ex.getMessage(),
                        "Training Error", JOptionPane.ERROR_MESSAGE);
                    ex.printStackTrace();
                }
            }
        }).start();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectSchoolYear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectSchoolYear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectSchoolYear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectSchoolYear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectSchoolYear().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Selectschoolyearbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> selectschoolyearcombobox;
    // End of variables declaration//GEN-END:variables
}
