/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.colesenrollmentsystem;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author aanpcoles
 */
public class GradesForm extends javax.swing.JFrame {
    int teachid = 0;

    Subjects currentSubject = new Subjects();
    int subjid = currentSubject.subjid;
    
    Students currentStudents = new Students();
    int studentid = currentStudents.studentid;
    /**
     * Creates new form GradesForm
     */
    public GradesForm() {
        initComponents();
        if (ColesEnrollmentSystem.db != null) {
            dblabel.setText(ColesEnrollmentSystem.db);
        }
        setLocationRelativeTo(null);
        teachid = Integer.parseInt(ColesEnrollmentSystem.uname.replaceAll("^([0-9]+).*", "$1")); //get teacher id
        this.setTitle(ColesEnrollmentSystem.db);
        showRecords();
    }

    public GradesForm(String user) {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        subjectsTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        PComboBox = new javax.swing.JComboBox<>();
        savebutton = new javax.swing.JButton();
        studentIDField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        gradesTable = new javax.swing.JTable();
        studentNameField = new javax.swing.JTextField();
        MComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        PFComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        FComboBox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        dblabel = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setText("Grade Form");

        subjectsTable.setBackground(new java.awt.Color(102, 102, 255));
        subjectsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Code", "Desc", "Units", "Schedule", "Students"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        subjectsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subjectsTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(subjectsTable);

        jLabel5.setText("Midterm");

        jLabel6.setText("PreFinal");

        jLabel7.setText("Final");

        PComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B+", "B", "C+", "C", "D", "F", "FD" }));
        PComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PComboBoxActionPerformed(evt);
            }
        });

        savebutton.setText("Save");
        savebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebuttonActionPerformed(evt);
            }
        });

        gradesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "StudID", "StudName", "Prelim", "Midterm", "PreFinal", "Final"
            }
        ));
        gradesTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gradesTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(gradesTable);

        studentNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentNameFieldActionPerformed(evt);
            }
        });

        MComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B+", "B", "C+", "C", "D", "F", "FD" }));
        MComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MComboBoxActionPerformed(evt);
            }
        });

        jLabel3.setText("StudID");

        PFComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B+", "B", "C+", "C", "D", "F", "FD" }));
        PFComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PFComboBoxActionPerformed(evt);
            }
        });

        jLabel4.setText("StudName");

        FComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B+", "B", "C+", "C", "D", "F", "FD" }));
        FComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FComboBoxActionPerformed(evt);
            }
        });

        jLabel8.setText("Prelim");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Exit");

        jMenuItem1.setText("Exit Form");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);
        jMenu2.add(jSeparator1);

        jMenuItem2.setText("Exit Application");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(dblabel, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(216, 216, 216)
                            .addComponent(jLabel2))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(36, 36, 36)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(studentIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(studentNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(PComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addGap(66, 66, 66)
                                            .addComponent(jLabel6)
                                            .addGap(70, 70, 70)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel7)
                                                .addComponent(savebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(MComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(PFComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(FComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(dblabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PFComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(savebutton)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.out.println("Closing StudentsForm");
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.out.println("Closing Application");
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void subjectsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subjectsTableMouseClicked
        int index = subjectsTable.getSelectedRow();

        TableModel table = subjectsTable.getModel();
        DefaultTableModel classTable = (DefaultTableModel) gradesTable.getModel();
        classTable.setRowCount(0);

        subjid = Integer.parseInt(String.valueOf(table.getValueAt(index, 0)));

        studentIDField.setText(null);
        studentNameField.setText(null);
        PComboBox.removeAllItems();
        MComboBox.removeAllItems();
        PFComboBox.removeAllItems();
        FComboBox.removeAllItems();

        showRecords();
    }//GEN-LAST:event_subjectsTableMouseClicked

    private void PComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PComboBoxActionPerformed
        String selectedItem = null;

        if (PComboBox.getSelectedItem() != null) {
            selectedItem = PComboBox.getSelectedItem().toString().trim();
        }
    }//GEN-LAST:event_PComboBoxActionPerformed

    private void savebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebuttonActionPerformed
        if (String.valueOf(studentIDField.getText()).isBlank()) {
            JOptionPane.showMessageDialog(null, "Please select a student first!");
            return;
        }

        String query, prelim, midterm, prefinal, finalterm;
        int enrollId = 0;

        prelim = PComboBox.getSelectedItem().toString().trim();
        midterm = MComboBox.getSelectedItem().toString().trim();
        prefinal = PFComboBox.getSelectedItem().toString().trim();
        finalterm = FComboBox.getSelectedItem().toString().trim();

        query = String.format("select eid from Enroll where subjid = %d and studid = %d;",
            subjid, studentid);

        ColesEnrollmentSystem system = new ColesEnrollmentSystem();
        system.DBConnect();

        try {
            system.rs = system.st.executeQuery(query);
            system.rs.next();
            enrollId = system.rs.getInt("eid");
        } catch (Exception e) {
            System.out.println("failed to get enroll Id of student: " + e);
        }

        query = "select count(*) count from Grades where eid = (select eid from Enroll where studid = "
        + studentid + " and subjid = " + subjid + ")";

        try {
            system.rs = system.st.executeQuery(query);
            int count = 0;
            if (system.rs.next()) count = system.rs.getInt("count");

            if (count > 0) {
                query = String.format("update Grades set Prelim = '%s', Midterm = '%s', Prefinal = '%s', Final = '%s' where"
                    + " eid = " + enrollId + ";",
                    prelim, midterm, prefinal, finalterm, enrollId);
                system.st.executeUpdate(query);
                JOptionPane.showMessageDialog(null, String.format("Successfully updated grades of student %d", studentid));
            } else {
                query = String.format("insert into Grades(eid, prelim, midterm, prefinal, final) values(%d, '%s', '%s', '%s', '%s')",
                    enrollId, prelim, midterm, prefinal, finalterm);
                system.st.executeUpdate(query);
                JOptionPane.showMessageDialog(null, String.format("Successfully graded student %d", studentid));
            }
        } catch (Exception e) {
            System.out.println("Failed to check if grades exists: " + e);
        }
        showRecords();
    }//GEN-LAST:event_savebuttonActionPerformed

    private void gradesTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gradesTableMouseClicked
        String prelimGrade, midtermGrade, prefinalGrade, finalGrade;
        int index = gradesTable.getSelectedRow();
        // Objects
        TableModel table = gradesTable.getModel();

        studentIDField.setText(String.valueOf(table.getValueAt(index, 0)));
        studentNameField.setText(String.valueOf(table.getValueAt(index, 1)));
        studentid = Integer.parseInt(String.valueOf(table.getValueAt(index, 0)));

        PComboBox.removeAllItems();
        MComboBox.removeAllItems();
        PFComboBox.removeAllItems();
        FComboBox.removeAllItems();

        String[] gradeOptions = {"", "A", "B+", "B", "C+", "C", "D", "F", "FD"};

        for (String g : gradeOptions) {
            PComboBox.addItem(g);
            MComboBox.addItem(g);
            PFComboBox.addItem(g);
            FComboBox.addItem(g);
        }

        // Get student's grades from table
        prelimGrade = String.valueOf(table.getValueAt(index, 2));
        midtermGrade = String.valueOf(table.getValueAt(index, 3));
        prefinalGrade = String.valueOf(table.getValueAt(index, 4));
        finalGrade = String.valueOf(table.getValueAt(index, 5));

        // Update comboBoxes with existing grades if present
        if (!prelimGrade.isBlank()) {
            PComboBox.setSelectedItem(prelimGrade);
        }
        if (!midtermGrade.isBlank()) {
            MComboBox.setSelectedItem(midtermGrade);
        }
        if (!prefinalGrade.isBlank()) {
            PFComboBox.setSelectedItem(prefinalGrade);
        }
        if (!finalGrade.isBlank()) {
            FComboBox.setSelectedItem(finalGrade);
        }
    }//GEN-LAST:event_gradesTableMouseClicked

    private void MComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MComboBoxActionPerformed
        String selectedItem = null;

        if (MComboBox.getSelectedItem() != null) {
            selectedItem = MComboBox.getSelectedItem().toString().trim(); 
        }
    }//GEN-LAST:event_MComboBoxActionPerformed

    private void PFComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PFComboBoxActionPerformed
        String selectedItem = null;

        if (PFComboBox.getSelectedItem() != null) {
            selectedItem = PFComboBox.getSelectedItem().toString().trim(); 
        }
    }//GEN-LAST:event_PFComboBoxActionPerformed

    private void FComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FComboBoxActionPerformed
        String selectedItem = null;

        if (FComboBox.getSelectedItem() != null) {
            selectedItem = FComboBox.getSelectedItem().toString().trim(); 
        }
    }//GEN-LAST:event_FComboBoxActionPerformed

    private void studentNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentNameFieldActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        DefaultTableModel tblmodel = (DefaultTableModel) subjectsTable.getModel();
        tblmodel.setRowCount(0);
        ColesEnrollmentSystem a = new ColesEnrollmentSystem();
        a.DBConnect();

        showRecords();
    }//GEN-LAST:event_formWindowOpened
    private void showRecords() {
        this.setTitle(ColesEnrollmentSystem.db);
        
        ColesEnrollmentSystem system = new ColesEnrollmentSystem();
        system.DBConnect();
        
        // Table setup
        DefaultTableModel subjectsTableModel = (DefaultTableModel) subjectsTable.getModel();
        DefaultTableModel gradesTableModel = (DefaultTableModel) gradesTable.getModel();

        subjectsTableModel.setRowCount(0); // Clear subjects table

        try {
            String query = "SELECT s.subjid, s.subjcode, s.subjdescription, s.subjschedule, s.subjunit, "
                    + "(SELECT COUNT(*) FROM Enroll e WHERE e.subjid = s.subjid) AS students "
                    + "FROM SubjectsTable s "
                    + "WHERE s.subjid IN (SELECT subid FROM Assign WHERE tid = " + teachid + ")";

            system.rs = system.st.executeQuery(query);

            while (system.rs.next()) {
                String subjectID = system.rs.getString("subjid");
                String code = system.rs.getString("subjcode");
                String description = system.rs.getString("subjdescription");
                String schedule = system.rs.getString("subjschedule");
                String units = system.rs.getString("subjunit");
                String students = system.rs.getString("students");

                String[] row = {subjectID, code, description, units, schedule, students};
                subjectsTableModel.addRow(row);
            }
        } catch (Exception error) {
            System.out.println("Failed to show subjects table: " + error);
        }

        // Check if a subject is selected
        if (subjid == 0) {
            return;
        }

        // GRADES TABLE
        gradesTableModel.setRowCount(0); // Clear grades table

        try {
            String query = "SELECT e.studid, s.Name, g.prelim, g.midterm, g.prefinal, g.final "
                    + "FROM Enroll e "
                    + "JOIN StudentsTable s ON e.studid = s.studentid "
                    + "LEFT JOIN Grades g ON g.eid = e.eid "
                    + "WHERE e.subjid = " + subjid;

            system.rs = system.st.executeQuery(query);

            while (system.rs.next()) {
                String studentID = system.rs.getString("studid");
                String studentName = system.rs.getString("name");
                String prelim = system.rs.getString("prelim");
                String midterm = system.rs.getString("midterm");
                String prefinal = system.rs.getString("prefinal");
                String finalterm = system.rs.getString("final");

                String[] row = {studentID, studentName, prelim, midterm, prefinal, finalterm};
                gradesTableModel.addRow(row);
            }

            System.out.println("Grades table updated successfully");
        } catch (Exception e) {
            System.out.println("Failed to update grades table: " + e);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GradesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GradesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GradesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GradesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GradesForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> FComboBox;
    private javax.swing.JComboBox<String> MComboBox;
    private javax.swing.JComboBox<String> PComboBox;
    private javax.swing.JComboBox<String> PFComboBox;
    private javax.swing.JTextField dblabel;
    private javax.swing.JTable gradesTable;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JButton savebutton;
    private javax.swing.JTextField studentIDField;
    private javax.swing.JTextField studentNameField;
    private javax.swing.JTable subjectsTable;
    // End of variables declaration//GEN-END:variables
}
