/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.colesenrollmentsystem;
import static com.mycompany.colesenrollmentsystem.ColesEnrollmentSystem.st;
import java.awt.Desktop;
import java.io.File;
import java.sql.*;
import java.time.Year;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author aanpcoles
 */

public class StudentsForm extends javax.swing.JFrame {
    private Enrolled enrolledHandler = new Enrolled();
    private static StudentsForm currentInstance;
    private static SubjectsForm subjectsFormInstance;
    String Name;
    

    /**
     * Creates new form StudentsForm
     */
    public StudentsForm() {
        initComponents();
        studid.setEditable(false);
        studid.setFocusable(false);

        setNextStudentID();
        currentInstance = this;
        showRecords();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        studid = new javax.swing.JTextField();
        Namefield = new javax.swing.JTextField();
        Addressfield = new javax.swing.JTextField();
        Coursefield = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Contactfield = new javax.swing.JTextField();
        emailfield = new javax.swing.JTextField();
        Yearlvlfield = new javax.swing.JTextField();
        Genderfield = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        SaveButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        enrollbutton = new javax.swing.JButton();
        dropbutton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        students = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        enrolltable = new javax.swing.JTable();
        dblabel = new javax.swing.JLabel();
        tor = new javax.swing.JButton();
        customyr = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Subjectsshortcut = new javax.swing.JMenuItem();
        Teachersshortcut = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel7.setText("STUDENT ENROLLMENT SYSTEM");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(204, 0, 153));

        jLabel6.setText("Student Year Level");

        jLabel9.setText("Student Email");

        jLabel1.setText("Student ID");

        jLabel2.setText("Student Name");

        jLabel3.setText("Student Address");

        jLabel4.setText("Student Course");

        jLabel5.setText("Student Gender");

        jLabel8.setText("Student Contact");

        Contactfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactfieldActionPerformed(evt);
            }
        });

        Yearlvlfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YearlvlfieldActionPerformed(evt);
            }
        });

        Genderfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenderfieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(studid, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Namefield, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Addressfield, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Contactfield, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailfield, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(Coursefield, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Genderfield)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(Yearlvlfield, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Namefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Addressfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Contactfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(emailfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(Coursefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Genderfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Yearlvlfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        DeleteButton.setText("Delete");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        UpdateButton.setText("Update");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        enrollbutton.setText("Enroll");
        enrollbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrollbuttonActionPerformed(evt);
            }
        });

        dropbutton.setText("Drop");
        dropbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SaveButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DeleteButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UpdateButton)
                .addGap(73, 73, 73))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(enrollbutton)
                .addGap(18, 18, 18)
                .addComponent(dropbutton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveButton)
                    .addComponent(DeleteButton)
                    .addComponent(UpdateButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enrollbutton)
                    .addComponent(dropbutton))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        students.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Student Name", "Student Address", "Student Contact", "Student Email", "Student Course", "Student Gender", "Student Year Level"
            }
        ));
        students.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(students);

        enrolltable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Subject ID", "Subject Code", "Subject Description", "Subject Schedule", "Subject Units"
            }
        ));
        jScrollPane2.setViewportView(enrolltable);

        dblabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dblabel.setText("jLabel10");

        tor.setText("TOR");
        tor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                torActionPerformed(evt);
            }
        });

        jMenuBar1.setBackground(new java.awt.Color(255, 102, 204));

        jMenu1.setText("Form");

        Subjectsshortcut.setText("Subjects");
        Subjectsshortcut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubjectsshortcutActionPerformed(evt);
            }
        });
        jMenu1.add(Subjectsshortcut);

        Teachersshortcut.setText("Teachers");
        Teachersshortcut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeachersshortcutActionPerformed(evt);
            }
        });
        jMenu1.add(Teachersshortcut);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Database");

        jMenuItem1.setText("FirstSemester");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("SecondSemester");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Summer");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Custom FirstSem");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Custom SecondSem");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Custom Summer");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tor)
                        .addGap(91, 91, 91)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(290, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(57, 57, 57))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(customyr, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(dblabel, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(dblabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(customyr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tor))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void clearFields() {
        studid.setText("");
        Namefield.setText("");
        Addressfield.setText("");
        Contactfield.setText("");
        emailfield.setText("");
        Coursefield.setText("");
        Genderfield.setText("");
        Yearlvlfield.setText("");
}
        public static StudentsForm getCurrentInstance() {
        return currentInstance;
    }

    public static void setSubjectsFormInstance(SubjectsForm instance) {
        subjectsFormInstance = instance;
    }
    
    public void showRecords() {
    DefaultTableModel tblmodel = (DefaultTableModel) students.getModel();
    tblmodel.setRowCount(0);
    ColesEnrollmentSystem a = new ColesEnrollmentSystem();
    a.DBConnect();

    try {
        String query = "SELECT studentid, Name, Address, Contact, email, Course, Gender, YearLevel FROM StudentsTable;";
        a.rs = a.st.executeQuery(query);

        while (a.rs.next()) {
            String i = a.rs.getString("studentid");
            String j = a.rs.getString("Name");
            String k = a.rs.getString("Address");
            String l = a.rs.getString("Contact");
            String m = a.rs.getString("email");
            String n = a.rs.getString("Course");
            String o = a.rs.getString("Gender");
            String p = a.rs.getString("YearLevel");

            tblmodel.addRow(new Object[]{i, j, k, l, m, n, o, p});
        }
        System.out.println("QUERY: " + query);

    } catch (Exception ex) {
        System.out.println("QUERY FAILED: " + ex.getMessage());
        ex.printStackTrace();
    }
}
    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        Students stud = new Students();
        stud.SaveRecord(
                Namefield.getText(),
                Addressfield.getText(),
                Contactfield.getText(),
                emailfield.getText(),
                Coursefield.getText(),
                Genderfield.getText(),
                Yearlvlfield.getText()
        );
        clearFields();
        showRecords();


    }//GEN-LAST:event_SaveButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        Students stud = new Students ();
        stud.DeleteRecord(Integer.parseInt(studid.getText()), Name);
        clearFields();
        showRecords();        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        Students stud = new Students ();
        stud.UpdateRecord(Integer.parseInt(studid.getText()), Namefield.getText(), Addressfield.getText(), Contactfield.getText(),emailfield.getText(), Coursefield.getText(), (String)Genderfield.getText(), (String)Yearlvlfield.getText());;
        clearFields();
        showRecords();
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void SubjectsshortcutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubjectsshortcutActionPerformed
        SubjectsForm a = new SubjectsForm();
        a.setVisible(true);
    }//GEN-LAST:event_SubjectsshortcutActionPerformed

    private void TeachersshortcutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeachersshortcutActionPerformed
        TeachersForm a = new TeachersForm();
        a.setVisible(true);
    }//GEN-LAST:event_TeachersshortcutActionPerformed

    private void ContactfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContactfieldActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Students b = new Students(); 
        DefaultTableModel tblmodel = (DefaultTableModel)students.getModel();
        tblmodel.setRowCount(0);
        ColesEnrollmentSystem a = new ColesEnrollmentSystem();
        a.DBConnect();// TODO add your handling code here:
        dblabel.setText(a.db);
        
    try {
        String query = "SELECT * FROM StudentsTable;";
            a.rs = a.st.executeQuery(query);
         
            while (a.rs.next())
            {
                String studentid = a.rs.getString("Studentid");
                String name = a.rs.getString("Name");
                String address = a.rs.getString("Address");
                String contact = a.rs.getString("Contact");
                String email = a.rs.getString("Email");
                String course = a.rs.getString("Course");
                String gender = a.rs.getString("Gender");
                String yearlvl = a.rs.getString("YearLevel");
                tblmodel.addRow(new Object[]{studentid, name, address, contact, email, course, gender, yearlvl});
            }
    }catch(Exception ex){
        System.out.println(ex);
      }
    }//GEN-LAST:event_formWindowOpened

    private void YearlvlfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YearlvlfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YearlvlfieldActionPerformed

    private void GenderfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenderfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GenderfieldActionPerformed

    private void studentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentsMouseClicked
        int selectedRow = students.getSelectedRow();
        
        String studentid = students.getValueAt(selectedRow, 0).toString();
        Name = students.getValueAt(selectedRow, 1).toString();
        String Address = students.getValueAt(selectedRow, 2).toString();
        String Course = students.getValueAt(selectedRow, 3).toString();
        String Gender = students.getValueAt(selectedRow, 4).toString();
        String Yearlvl = students.getValueAt(selectedRow, 5).toString();
        String Contact = students.getValueAt(selectedRow, 6).toString();
        String email = students.getValueAt(selectedRow, 7).toString();
        
        studid.setText(studentid);
        Namefield.setText(Name);
        Addressfield.setText(Address);
        Contactfield.setText(Contact);
        Coursefield.setText(Course);
        Genderfield.setText(Gender);
        Yearlvlfield.setText(Yearlvl);
        emailfield.setText(email); 
        
        ShowEnrollRec();
    }//GEN-LAST:event_studentsMouseClicked
    
    private void enrollbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrollbuttonActionPerformed
        if (studid.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select a student first.", "No Student Selected", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (subjectsFormInstance == null) {
            JOptionPane.showMessageDialog(this, "Please open the Subjects form first.", "Subjects Form Not Open", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String selectedSubjID = subjectsFormInstance.getSelectedSubjectID();
        if (selectedSubjID == null || selectedSubjID.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select a subject in the Subjects form first.", "No Subject Selected", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            int studentID = Integer.parseInt(studid.getText());
            int subjectID = Integer.parseInt(selectedSubjID);

            String confirmMessage = "Enroll Student ID: " + studentID + " to Subject ID: " + subjectID;
            int choice = JOptionPane.showConfirmDialog(this, confirmMessage, "Confirm Enrollment", JOptionPane.OK_CANCEL_OPTION);

            if (choice == JOptionPane.OK_OPTION) {
                enrolledHandler.setsubjid(subjectID);
                String result = enrolledHandler.enrollStud(studentID);

                if (result.contains("successfully")) {
                    JOptionPane.showMessageDialog(this, "Student: " + studentID + " enrolled to " + subjectID + ".", "Enrollment Successful", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, result, "Enrollment Failed", JOptionPane.ERROR_MESSAGE);
                }

                ShowEnrollRec();
                subjectsFormInstance.ShowClassList();
            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Invalid student or subject ID.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_enrollbuttonActionPerformed

    private void dropbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropbuttonActionPerformed
        int selectedRow = enrolltable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a subject to drop.", "No Subject Selected", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (studid.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select a student first.", "No Student Selected", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            int studentID = Integer.parseInt(studid.getText());
            String subjID = enrolltable.getValueAt(selectedRow, 0).toString();
            int subjectID = Integer.parseInt(subjID);

            String confirmMessage = "Drop subject: " + subjectID + " enrolled by Student: " + studentID;
            int choice = JOptionPane.showConfirmDialog(this, confirmMessage, "Confirm Drop Subject", JOptionPane.OK_CANCEL_OPTION);

            if (choice == JOptionPane.OK_OPTION) {
                enrolledHandler.setsubjid(subjectID);
                String result = enrolledHandler.DropSubj(studentID);

                if (result.contains("successfully")) {
                    JOptionPane.showMessageDialog(this, "Student: " + studentID + " dropped Subject: " + subjectID, "Drop Successful", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, result, "Drop Failed", JOptionPane.ERROR_MESSAGE);
                }

                ShowEnrollRec();

                if (subjectsFormInstance != null) {
                    subjectsFormInstance.ShowClassList();
                }
            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Invalid student or subject ID.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_dropbuttonActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        int firstYear = Year.now().getValue();
        int secondYear = firstYear + 1;
        String database = "2ndSemSY" + firstYear + "_" + secondYear;
        String query = "SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = '" + database + "'";
        ResultSet rs;

        try {
            rs = st.executeQuery(query);
            if (rs.next()) {
                ColesEnrollmentSystem a = new ColesEnrollmentSystem();
                a.db = database;
                a.DBConnect();
                showRecords();
                JOptionPane.showMessageDialog(null, "Connected to: " + database);
            } else {
                st.executeUpdate("CREATE DATABASE " + database);
                st.executeUpdate("USE " + database);
                String[] queries = ColesEnrollmentSystem.createDatabase.split(";");;
                for (String q : queries) {
                    if (!q.trim().isEmpty()) {
                        st.executeUpdate(q);
                    }
                }
                JOptionPane.showMessageDialog(null, "Database created: " + database);
            }
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        int firstYear = Year.now().getValue();
        int secondYear = firstYear + 1;
        String database = "1stSemSY" + firstYear + "_" + secondYear;
        String query = "SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = '" + database + "'";
        ResultSet rs;
        try {
            rs = st.executeQuery(query);
            if (rs.next()) {
                ColesEnrollmentSystem a = new ColesEnrollmentSystem();
                a.db = database;
                a.DBConnect();
                showRecords();
                JOptionPane.showMessageDialog(null, "Connected to: " + database);
            } else {
                st.executeUpdate("CREATE DATABASE " + database);
                st.executeUpdate("USE " + database);
                String[] queries = ColesEnrollmentSystem.createDatabase.split(";");
                for (String q : queries) {
                    if (!q.trim().isEmpty()) {
                        st.executeUpdate(q);
                    }
                }
                JOptionPane.showMessageDialog(null, "Database created: " + database);
            }
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        int firstYear = Year.now().getValue();
        int secondYear = firstYear + 1;
        String database = "SummerSY" + firstYear + "_" + secondYear;
        String query = "SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = '" + database + "'";
        ResultSet rs;
        try {
            rs = st.executeQuery(query);
            if (rs.next()) {
                ColesEnrollmentSystem a = new ColesEnrollmentSystem();
                a.db = database;
                a.DBConnect();
                showRecords();
                JOptionPane.showMessageDialog(null, "Connected to: " + database);
            } else {
                st.executeUpdate("CREATE DATABASE " + database);
                st.executeUpdate("USE " + database);
                String[] queries = ColesEnrollmentSystem.createDatabase.split(";");
                for (String q : queries) {
                    if (!q.trim().isEmpty()) {
                        st.executeUpdate(q);
                    }
                }
                JOptionPane.showMessageDialog(null, "Database created: " + database);
            }
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void torActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_torActionPerformed
//        try {
//            Reports.userType = true;
//            new Reports();
//
//            File pdfFile = new File(Reports.ADMIN_PATH);
//            if (pdfFile.exists()) {
//                if (Desktop.isDesktopSupported()) {
//                    Desktop.getDesktop().open(pdfFile);
//                } else {
//                    System.out.println("AWT Desktop not supported!");
//                }
//            } else {
//                System.out.println("TOR doesnt exist");
//            }
//        } catch (Exception e) {
//            System.out.println("error" + e);
//        }
        
        int row = students.getSelectedRow();
        int studId = Integer.parseInt(students.getValueAt(row, 0).toString());
        String studName = students.getValueAt(row, 1).toString();

        try {
            Reports report = new Reports();
            report.createTORPDF(studId);
        } catch (Exception e) {
            System.out.println("Failed to Print TOP");
        }
        ColesEnrollmentSystem system = new ColesEnrollmentSystem();
        system.DBConnect();
    }//GEN-LAST:event_torActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // customyr
        String today = String.valueOf(customyr.getText());
        String schoolYear = String.format("1stSem_Sy%s_%d", today, Integer.parseInt(today) + 1);

        ColesEnrollmentSystem.DBConnect();

        try {
            ColesEnrollmentSystem.st.executeUpdate(String.format("CREATE DATABASE IF NOT EXISTS %s", schoolYear));
            ColesEnrollmentSystem.db = schoolYear;
            ColesEnrollmentSystem.DBConnect();
            showRecords();
            JOptionPane.showMessageDialog(null, "Selected" + schoolYear);
            dblabel.setText(schoolYear);

            ColesEnrollmentSystem.st.executeUpdate("CREATE TABLE StudentsTable (studentid INT PRIMARY KEY AUTO_INCREMENT, Name TEXT, Address TEXT, Contact TEXT, email TEXT, Course TEXT, Gender TEXT, YearLevel TEXT)AUTO_INCREMENT = 1001;\n"
            );

            ColesEnrollmentSystem.st.executeUpdate("CREATE TABLE SubjectsTable (subjid INT PRIMARY KEY AUTO_INCREMENT, subjcode TEXT, subjdescription TEXT, subjschedule TEXT, subjunit INT) AUTO_INCREMENT = 2001;\n"
            );
            ColesEnrollmentSystem.st.executeUpdate("CREATE TABLE TeachersTable (teachid INT PRIMARY KEY AUTO_INCREMENT, teachname TEXT, teachaddress TEXT, teachcontact TEXT, teachemail TEXT, teachdept TEXT) AUTO_INCREMENT = 3001;\n"
            );
            ColesEnrollmentSystem.st.executeUpdate("CREATE TABLE Enroll (eid INT PRIMARY KEY AUTO_INCREMENT, studid INT, subjid INT, UNIQUE KEY unique_stud_subj (studid, subjid), FOREIGN KEY (studid) REFERENCES StudentsTable(studentid) ON DELETE CASCADE, FOREIGN KEY (subjid) REFERENCES SubjectsTable(subjid) ON DELETE CASCADE);\n"
            );
            ColesEnrollmentSystem.st.executeUpdate("CREATE TABLE Assign (subid INT UNIQUE, tid INT, FOREIGN KEY (subid) REFERENCES SubjectsTable(subjid) ON DELETE CASCADE, FOREIGN KEY (tid) REFERENCES TeachersTable(teachid) ON DELETE CASCADE);\n"
            );
            ColesEnrollmentSystem.st.executeUpdate("CREATE TABLE Grades (gradesid INT PRIMARY KEY AUTO_INCREMENT, eid INT UNIQUE, prelim TEXT, midterm TEXT, prefinal TEXT, final TEXT, FOREIGN KEY (eid) REFERENCES Enroll(eid) ON DELETE CASCADE);\n"
            );
            ColesEnrollmentSystem.st.executeUpdate("CREATE TABLE TransactionCharges (transac INT PRIMARY KEY AUTO_INCREMENT, department TEXT, subjunit DECIMAL(10,2), insurance DECIMAL(10,2), computer DECIMAL(10,2), laboratory DECIMAL(10,2), cultural DECIMAL(10,2), library DECIMAL(10,2), facility DECIMAL(10,2));\n"
            );
            ColesEnrollmentSystem.st.executeUpdate("CREATE TABLE Invoice (Transacid INT PRIMARY KEY AUTO_INCREMENT, invoicenum INT UNIQUE, studid INT, FOREIGN KEY (studid) REFERENCES StudentsTable(studentid) ON DELETE CASCADE);\n"
            );

            JOptionPane.showMessageDialog(null, "CREATED " + schoolYear);

        } catch (Exception e) {
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        String today = String.valueOf(customyr.getText());
        String schoolYear = String.format("2ndSem_Sy%s_%d", today, Integer.parseInt(today) + 1);

        ColesEnrollmentSystem.DBConnect();

        try {
            ColesEnrollmentSystem.st.executeUpdate(String.format("CREATE DATABASE IF NOT EXISTS %s", schoolYear));
            ColesEnrollmentSystem.db = schoolYear;
            ColesEnrollmentSystem.DBConnect();
            showRecords();
            JOptionPane.showMessageDialog(null, "Selected" + schoolYear);
            dblabel.setText(schoolYear);

            ColesEnrollmentSystem.st.executeUpdate("CREATE TABLE StudentsTable (studentid INT PRIMARY KEY AUTO_INCREMENT, Name TEXT, Address TEXT, Contact TEXT, email TEXT, Course TEXT, Gender TEXT, YearLevel TEXT)AUTO_INCREMENT = 1001;\n"
            );

            ColesEnrollmentSystem.st.executeUpdate("CREATE TABLE SubjectsTable (subjid INT PRIMARY KEY AUTO_INCREMENT, subjcode TEXT, subjdescription TEXT, subjschedule TEXT, subjunit INT) AUTO_INCREMENT = 2001;\n"
            );
            ColesEnrollmentSystem.st.executeUpdate("CREATE TABLE TeachersTable (teachid INT PRIMARY KEY AUTO_INCREMENT, teachname TEXT, teachaddress TEXT, teachcontact TEXT, teachemail TEXT, teachdept TEXT) AUTO_INCREMENT = 3001;\n"
            );
            ColesEnrollmentSystem.st.executeUpdate("CREATE TABLE Enroll (eid INT PRIMARY KEY AUTO_INCREMENT, studid INT, subjid INT, UNIQUE KEY unique_stud_subj (studid, subjid), FOREIGN KEY (studid) REFERENCES StudentsTable(studentid) ON DELETE CASCADE, FOREIGN KEY (subjid) REFERENCES SubjectsTable(subjid) ON DELETE CASCADE);\n"
            );
            ColesEnrollmentSystem.st.executeUpdate("CREATE TABLE Assign (subid INT UNIQUE, tid INT, FOREIGN KEY (subid) REFERENCES SubjectsTable(subjid) ON DELETE CASCADE, FOREIGN KEY (tid) REFERENCES TeachersTable(teachid) ON DELETE CASCADE);\n"
            );
            ColesEnrollmentSystem.st.executeUpdate("CREATE TABLE Grades (gradesid INT PRIMARY KEY AUTO_INCREMENT, eid INT UNIQUE, prelim TEXT, midterm TEXT, prefinal TEXT, final TEXT, FOREIGN KEY (eid) REFERENCES Enroll(eid) ON DELETE CASCADE);\n"
            );
            ColesEnrollmentSystem.st.executeUpdate("CREATE TABLE TransactionCharges (transac INT PRIMARY KEY AUTO_INCREMENT, department TEXT, subjunit DECIMAL(10,2), insurance DECIMAL(10,2), computer DECIMAL(10,2), laboratory DECIMAL(10,2), cultural DECIMAL(10,2), library DECIMAL(10,2), facility DECIMAL(10,2));\n"
            );
            ColesEnrollmentSystem.st.executeUpdate("CREATE TABLE Invoice (Transacid INT PRIMARY KEY AUTO_INCREMENT, invoicenum INT UNIQUE, studid INT, FOREIGN KEY (studid) REFERENCES StudentsTable(studentid) ON DELETE CASCADE);\n"
            );

            JOptionPane.showMessageDialog(null, "CREATED " + schoolYear);

        } catch (Exception e) {
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        String today = String.valueOf(customyr.getText());
        String schoolYear = String.format("Summer_Sy%s_%d", today, Integer.parseInt(today) + 1);

        ColesEnrollmentSystem.DBConnect();

        try {
            ColesEnrollmentSystem.st.executeUpdate(String.format("CREATE DATABASE IF NOT EXISTS %s", schoolYear));
            ColesEnrollmentSystem.db = schoolYear;
            ColesEnrollmentSystem.DBConnect();
            showRecords();
            JOptionPane.showMessageDialog(null, "Selected" + schoolYear);
            dblabel.setText(schoolYear);

            ColesEnrollmentSystem.st.executeUpdate("CREATE TABLE StudentsTable (studentid INT PRIMARY KEY AUTO_INCREMENT, Name TEXT, Address TEXT, Contact TEXT, email TEXT, Course TEXT, Gender TEXT, YearLevel TEXT)AUTO_INCREMENT = 1001;\n"
            );
            
            ColesEnrollmentSystem.st.executeUpdate("CREATE TABLE SubjectsTable (subjid INT PRIMARY KEY AUTO_INCREMENT, subjcode TEXT, subjdescription TEXT, subjschedule TEXT, subjunit INT) AUTO_INCREMENT = 2001;\n"
            );
            ColesEnrollmentSystem.st.executeUpdate("CREATE TABLE TeachersTable (teachid INT PRIMARY KEY AUTO_INCREMENT, teachname TEXT, teachaddress TEXT, teachcontact TEXT, teachemail TEXT, teachdept TEXT) AUTO_INCREMENT = 3001;\n"
            );
            ColesEnrollmentSystem.st.executeUpdate("CREATE TABLE Enroll (eid INT PRIMARY KEY AUTO_INCREMENT, studid INT, subjid INT, UNIQUE KEY unique_stud_subj (studid, subjid), FOREIGN KEY (studid) REFERENCES StudentsTable(studentid) ON DELETE CASCADE, FOREIGN KEY (subjid) REFERENCES SubjectsTable(subjid) ON DELETE CASCADE);\n"
            );
            ColesEnrollmentSystem.st.executeUpdate("CREATE TABLE Assign (subid INT UNIQUE, tid INT, FOREIGN KEY (subid) REFERENCES SubjectsTable(subjid) ON DELETE CASCADE, FOREIGN KEY (tid) REFERENCES TeachersTable(teachid) ON DELETE CASCADE);\n"
            );
            ColesEnrollmentSystem.st.executeUpdate("CREATE TABLE Grades (gradesid INT PRIMARY KEY AUTO_INCREMENT, eid INT UNIQUE, prelim TEXT, midterm TEXT, prefinal TEXT, final TEXT, FOREIGN KEY (eid) REFERENCES Enroll(eid) ON DELETE CASCADE);\n"
            );
            ColesEnrollmentSystem.st.executeUpdate("CREATE TABLE TransactionCharges (transac INT PRIMARY KEY AUTO_INCREMENT, department TEXT, subjunit DECIMAL(10,2), insurance DECIMAL(10,2), computer DECIMAL(10,2), laboratory DECIMAL(10,2), cultural DECIMAL(10,2), library DECIMAL(10,2), facility DECIMAL(10,2));\n"
            );
            ColesEnrollmentSystem.st.executeUpdate("CREATE TABLE Invoice (Transacid INT PRIMARY KEY AUTO_INCREMENT, invoicenum INT UNIQUE, studid INT, FOREIGN KEY (studid) REFERENCES StudentsTable(studentid) ON DELETE CASCADE);\n"
            );

            JOptionPane.showMessageDialog(null, "CREATED " + schoolYear);

        } catch (Exception e) {
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed
    
    private void ShowEnrollRec() {
        if (studid.getText().isEmpty()) {
            return;
        }

        try {
            int studID = Integer.parseInt(studid.getText());
            DefaultTableModel tblmodel = (DefaultTableModel) enrolltable.getModel();
            tblmodel.setRowCount(0);

            ColesEnrollmentSystem conn = new ColesEnrollmentSystem();
            conn.DBConnect();

            String query = "SELECT s.subjid, s.subjcode, s.subjdescription, s.subjschedule, s.subjunit "
                    + "FROM SubjectsTable s "
                    + "INNER JOIN Enroll e ON s.subjid = e.subjid "
                    + "WHERE e.studid = ?";

            PreparedStatement ps = conn.con.prepareStatement(query);
            ps.setInt(1, studID);
            ResultSet rs = ps.executeQuery();

            boolean hasResults = false;
            while (rs.next()) {
                hasResults = true;
                String[] item = {
                    rs.getString("subjid"),
                    rs.getString("subjcode"),
                    rs.getString("subjdescription"),
                    rs.getString("subjschedule"),
                    rs.getString("subjunit")
                };
                tblmodel.addRow(item);
            }

            if (!hasResults) {
                JOptionPane.showMessageDialog(null, "No subjects enrolled for student ID: " + studID);
            }

        } catch (Exception ex) {
            System.out.println("Error showing enrolled subjects: " + ex.getMessage());
        }
    }

    private void setNextStudentID() {
        ColesEnrollmentSystem conn = new ColesEnrollmentSystem();
        conn.DBConnect();

        int nextID = 1001;
        try {
            String query = "SELECT COUNT(*) FROM StudentsTable";
            conn.rs = conn.st.executeQuery(query);
            if (conn.rs.next()) {
                int count = conn.rs.getInt(1);
                nextID = 1001 + count;
            }
        } catch (Exception ex) {
            System.out.println("Error getting next ID: " + ex);
        }

        studid.setText(String.valueOf(nextID));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentsForm().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Addressfield;
    private javax.swing.JTextField Contactfield;
    private javax.swing.JTextField Coursefield;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JTextField Genderfield;
    private javax.swing.JTextField Namefield;
    private javax.swing.JButton SaveButton;
    private javax.swing.JMenuItem Subjectsshortcut;
    private javax.swing.JMenuItem Teachersshortcut;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JTextField Yearlvlfield;
    private javax.swing.JTextField customyr;
    private javax.swing.JLabel dblabel;
    private javax.swing.JButton dropbutton;
    private javax.swing.JTextField emailfield;
    private javax.swing.JButton enrollbutton;
    private javax.swing.JTable enrolltable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable students;
    private javax.swing.JTextField studid;
    private javax.swing.JButton tor;
    // End of variables declaration//GEN-END:variables
}
