/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.colesenrollmentsystem;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Arch Coles
 */
public class SubjectsForm extends javax.swing.JFrame {
     Subjects subj = new Subjects();
    /**
     * Creates new form SubjectsForm
     */
    public SubjectsForm() {
        initComponents();
        showRecords();
        
        subjid.setEditable(false);
        subjid.setFocusable(false);
        setNextSubjectID();

        TeachersForm.setSubjectsFormInstance(this);
        StudentsForm.setSubjectsFormInstance(this);
    }
    public void clearFields() {
        subjid.setText("");
        subjcode.setText("");
        subjdescription.setText("");
        subjschedule.setText("");
        subjunit.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        subjects = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        subjid = new javax.swing.JTextField();
        subjcode = new javax.swing.JTextField();
        subjdescription = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        subjschedule = new javax.swing.JTextField();
        subjunit = new javax.swing.JTextField();
        SaveButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        classlist = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Studentsbutton = new javax.swing.JMenuItem();
        Teachersbutton = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel7.setText("SUBJECTS");

        subjects.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Code", "Description", "Schedule", "Units"
            }
        ));
        subjects.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subjectsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(subjects);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(204, 0, 153));

        jLabel24.setText("Subject Units");

        subjid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjidActionPerformed(evt);
            }
        });

        jLabel1.setText("Subject ID");

        jLabel2.setText("Subject Code");

        jLabel3.setText("Subject Description");

        jLabel25.setText("Subject Schedule");

        subjschedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjscheduleActionPerformed(evt);
            }
        });

        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        DeleteButton.setText("Delete");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        UpdateButton.setText("Update");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel25)
                            .addComponent(jLabel24))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(subjid, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subjcode, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subjdescription, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subjschedule, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subjunit, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(SaveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DeleteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UpdateButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subjid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subjcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subjdescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(subjschedule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(subjunit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveButton)
                    .addComponent(DeleteButton)
                    .addComponent(UpdateButton))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        classlist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Student ID", "Student Name", "Student Address", "Student Contact", "Student Email", "Student Course", "Student Gender", "Student Year Level"
            }
        ));
        jScrollPane2.setViewportView(classlist);

        jMenu1.setText("Form");

        Studentsbutton.setText("Students");
        Studentsbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentsbuttonActionPerformed(evt);
            }
        });
        jMenu1.add(Studentsbutton);

        Teachersbutton.setText("Teachers");
        Teachersbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeachersbuttonActionPerformed(evt);
            }
        });
        jMenu1.add(Teachersbutton);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(383, 383, 383)
                        .addComponent(jLabel7)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel7)
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public String getSelectedSubjectID() {
        if (subjid.getText() != null && !subjid.getText().trim().isEmpty()) {
            return subjid.getText().trim();
        }
        return null;
    }
    
    public void showRecords() {
        DefaultTableModel tblmodel = (DefaultTableModel) subjects.getModel();
        tblmodel.setRowCount(0);

        ColesEnrollmentSystem conn = new ColesEnrollmentSystem();
        conn.DBConnect();

        try {
            String query = "SELECT subjid, subjcode, subjdescription, subjschedule, subjunit FROM SubjectsTable";
            conn.rs = conn.st.executeQuery(query);

            while (conn.rs.next()) {
                String subjid = conn.rs.getString("subjid");
                String subjcode = conn.rs.getString("subjcode");
                String description = conn.rs.getString("subjdescription");
                String schedule = conn.rs.getString("subjschedule");
                String unit = conn.rs.getString("subjunit");

                tblmodel.addRow(new Object[]{subjid, subjcode, description, schedule, unit});
            }

            System.out.println("QUERY SUCCESS: " + query);

        } catch (Exception ex) {
            System.out.println("QUERY FAILED: " + ex.getMessage());
            ex.printStackTrace();
        }

        setNextSubjectID();
    }
    private void setNextSubjectID() {
        ColesEnrollmentSystem conn = new ColesEnrollmentSystem();
        conn.DBConnect();

        int nextID = 2001;
        try {
            String query = "SELECT COUNT(*) FROM SubjectsTable";
            conn.rs = conn.st.executeQuery(query);

            if (conn.rs.next()) {
                int count = conn.rs.getInt(1);
                nextID = 2001 + count;
                System.out.println("Subject count: " + count);
            }
        } catch (Exception ex) {
            System.out.println("Error getting next subject ID: " + ex);
        }

        subjid.setText(String.valueOf(nextID));
        System.out.println("Next subject ID set to: " + nextID); 
    }

    public void ShowClassList() {
        if (subjid.getText().isEmpty()) {
            return;
        }

        try {
            int subjID = Integer.parseInt(subjid.getText());
            DefaultTableModel tblmodel = (DefaultTableModel) classlist.getModel();
            tblmodel.setRowCount(0);

            ColesEnrollmentSystem conn = new ColesEnrollmentSystem();
            conn.DBConnect();

            String query = "SELECT s.studentid, s.Name, s.Address, s.Contact, s.Email, s.Course, s.Gender, s.YearLevel "
                    + "FROM StudentsTable s "
                    + "INNER JOIN Enroll e ON s.studentid = e.studid "
                    + "WHERE e.subjid = ?";

            PreparedStatement ps = conn.con.prepareStatement(query);
            ps.setInt(1, subjID);
            ResultSet rs = ps.executeQuery();

            boolean hasResults = false;
            while (rs.next()) {
                hasResults = true;
                String[] item = {
                    rs.getString("studentid"),
                    rs.getString("Name"),
                    rs.getString("Address"),
                    rs.getString("Contact"),
                    rs.getString("Email"),
                    rs.getString("Course"),
                    rs.getString("Gender"),
                    rs.getString("YearLevel")
                };
                tblmodel.addRow(item);
            }

            if (!hasResults) {
                JOptionPane.showMessageDialog(null, "No students enrolled in subject ID: " + subjID);
            }

        } catch (Exception ex) {
            System.out.println("Error showing class list: " + ex.getMessage());
        }
    }
    private void subjectsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subjectsMouseClicked
        int selectedRow = subjects.getSelectedRow();
        DefaultTableModel tblmodel = (DefaultTableModel) subjects.getModel();

        subjid.setText(tblmodel.getValueAt(selectedRow, 0).toString());
        subjcode.setText(tblmodel.getValueAt(selectedRow, 1).toString());
        subjdescription.setText(tblmodel.getValueAt(selectedRow, 2).toString());
        subjschedule.setText(tblmodel.getValueAt(selectedRow, 3).toString());
        subjunit.setText(tblmodel.getValueAt(selectedRow, 4).toString());
        ShowClassList();
    }//GEN-LAST:event_subjectsMouseClicked

    private void subjscheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjscheduleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjscheduleActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        subj.SaveRecord(Integer.parseInt(subjid.getText()), subjcode.getText(), subjdescription.getText(), subjschedule.getText(), Integer.parseInt (subjunit.getText()));
        clearFields();
        showRecords();
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed

        subj.DeleteRecord(Integer.parseInt(subjid.getText()));
        clearFields();
        showRecords();        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        subj.UpdateRecord(Integer.parseInt(subjid.getText()), subjcode.getText(), subjdescription.getText(), subjschedule.getText(), Integer.parseInt (subjunit.getText()));      
        clearFields();
        showRecords();
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void subjidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjidActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        DefaultTableModel tblmodel = (DefaultTableModel) subjects.getModel();
        tblmodel.setRowCount(0);
        ColesEnrollmentSystem a = new ColesEnrollmentSystem();
        a.DBConnect();

        try {
            String query = "SELECT * FROM SubjectsTable;";
            a.rs = a.st.executeQuery(query);

            while (a.rs.next()) {
                String subjid = a.rs.getString("subjid");
                String subjcode = a.rs.getString("subjcode");
                String subjdescription = a.rs.getString("subjdescription");
                String subjschedule = a.rs.getString("subjschedule");
                String subjunit= a.rs.getString("subjunit");
                tblmodel.addRow(new Object[]{subjid, subjcode, subjdescription, subjschedule, subjunit});
            }
        } catch (Exception ex) {
            System.out.println(ex);
        }        
    }//GEN-LAST:event_formWindowOpened

    private void StudentsbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentsbuttonActionPerformed
        StudentsForm a = new StudentsForm();
        a.setVisible(true);       
    }//GEN-LAST:event_StudentsbuttonActionPerformed

    private void TeachersbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeachersbuttonActionPerformed
        TeachersForm a = new TeachersForm();
        a.setVisible(true);   
    }//GEN-LAST:event_TeachersbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubjectsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubjectsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubjectsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubjectsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubjectsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton SaveButton;
    private javax.swing.JMenuItem Studentsbutton;
    private javax.swing.JMenuItem Teachersbutton;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JTable classlist;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField subjcode;
    private javax.swing.JTextField subjdescription;
    private javax.swing.JTable subjects;
    private javax.swing.JTextField subjid;
    private javax.swing.JTextField subjschedule;
    private javax.swing.JTextField subjunit;
    // End of variables declaration//GEN-END:variables
}
