/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.colesenrollmentsystem;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Arch Coles
 */
public class TeachersForm extends javax.swing.JFrame {
    
     Teachers teach = new Teachers();
    /**
     * Creates new form TeachersForm
     */
    private Assign assignHandler = new Assign();
    private static TeachersForm currentInstance;
    private static SubjectsForm subjectsFormInstance;
    
    public TeachersForm() {
        initComponents();
        setNextTeacherID();
        teachid.setEditable(false);
        teachid.setFocusable(false);
        showRecords();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public static TeachersForm getCurrentInstance() {
        return currentInstance;
    }

    public static void setSubjectsFormInstance(SubjectsForm instance) {
        subjectsFormInstance = instance;
    }
    public SubjectsForm getSubjectsFormInstance() {
        return subjectsFormInstance;
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Teachers = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        teachid = new javax.swing.JTextField();
        teachname = new javax.swing.JTextField();
        teachaddress = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        teachcontact = new javax.swing.JTextField();
        teachemail = new javax.swing.JTextField();
        SaveButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        teachdept = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        assignbutton = new javax.swing.JButton();
        deletesubjbutton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        assigntable = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Studentsmenu = new javax.swing.JMenuItem();
        Subjectsmenu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Teachers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Address", "Contact", "Email", "Department"
            }
        ));
        Teachers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TeachersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Teachers);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(204, 0, 153));

        jLabel24.setText("Teachers Email");

        teachid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teachidActionPerformed(evt);
            }
        });

        teachname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teachnameActionPerformed(evt);
            }
        });

        jLabel1.setText("Teachers ID");

        jLabel2.setText("Teachers Name");

        jLabel3.setText("Teachers Address");

        jLabel25.setText("Teachers Contact");

        teachcontact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teachcontactActionPerformed(evt);
            }
        });

        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        DeleteButton.setText("Delete");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        UpdateButton.setText("Update");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        jLabel26.setText("Teachers Department");

        assignbutton.setText("Assign");
        assignbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignbuttonActionPerformed(evt);
            }
        });

        deletesubjbutton.setText("Delete");
        deletesubjbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletesubjbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel26))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(teachid, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(teachname, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(teachaddress, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(teachcontact, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(teachemail, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                    .addComponent(teachdept, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(SaveButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DeleteButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UpdateButton))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(assignbutton)
                        .addGap(18, 18, 18)
                        .addComponent(deletesubjbutton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teachid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teachname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teachaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(teachcontact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(teachemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teachdept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveButton)
                    .addComponent(DeleteButton)
                    .addComponent(UpdateButton))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assignbutton)
                    .addComponent(deletesubjbutton))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel7.setText("TEACHERS");

        assigntable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Subject ID", "Subject Code", "Subject Description", "Subject Schedule", "Subject Units"
            }
        ));
        jScrollPane2.setViewportView(assigntable);

        jMenu1.setText("Form");

        Studentsmenu.setText("Students");
        Studentsmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentsmenuActionPerformed(evt);
            }
        });
        jMenu1.add(Studentsmenu);

        Subjectsmenu.setText("Subjects");
        Subjectsmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubjectsmenuActionPerformed(evt);
            }
        });
        jMenu1.add(Subjectsmenu);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(39, 39, 39))
            .addGroup(layout.createSequentialGroup()
                .addGap(354, 354, 354)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void clearFields() {
        teachid.setText("");
        teachname.setText("");
        teachaddress.setText("");
        teachcontact.setText("");
        teachemail.setText("");
        teachdept.setText("");
    }
    public void showRecords() {
        DefaultTableModel tblmodel = (DefaultTableModel) Teachers.getModel();
        tblmodel.setRowCount(0);

        try {
            ColesEnrollmentSystem a = new ColesEnrollmentSystem();
            a.DBConnect();

            String query = "SELECT teachid, teachname, teachaddress, teachcontact, teachemail, teachdept FROM TeachersTable";
            PreparedStatement ps = a.con.prepareStatement(query);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                String i = rs.getString("teachid");
                String j = rs.getString("teachname");
                String k = rs.getString("teachaddress");
                String l = rs.getString("teachcontact");
                String m = rs.getString("teachemail");
                String n = rs.getString("teachdept");

                tblmodel.addRow(new Object[]{i, j, k, l, m, n});
            }

            rs.close();
            ps.close();
            a.con.close();

            System.out.println("QUERY: " + query);

        } catch (Exception ex) {
            System.out.println("QUERY FAILED: " + ex.getMessage());
            ex.printStackTrace();
        }
    }

    
    private void ShowAssignRec() {
        if (teachid.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select a teacher first.", "No Teacher Selected", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            int teachID = Integer.parseInt(teachid.getText());

            if (assigntable.getModel() == null || !(assigntable.getModel() instanceof DefaultTableModel)) {
                assigntable.setModel(new DefaultTableModel(
                        new Object[][]{},
                        new String[]{"Subject ID", "Code", "Description", "Schedule", "Units"}
                ));
            }

            DefaultTableModel tblmodel = (DefaultTableModel) assigntable.getModel();
            tblmodel.setRowCount(0);

            ColesEnrollmentSystem conn = new ColesEnrollmentSystem();
            conn.DBConnect();

            String query = "SELECT s.subjid, s.subjcode, s.subjdescription, s.subjschedule, s.subjunit "
                    + "FROM SubjectsTable s "
                    + "INNER JOIN Assign a ON s.subjid = a.subid "
                    + "WHERE a.tid = ?";

            PreparedStatement ps = conn.con.prepareStatement(query);
            ps.setInt(1, teachID);
            ResultSet rs = ps.executeQuery();

            boolean hasResults = false;
            while (rs.next()) {
                hasResults = true;

                String subjid = rs.getString("subjid");
                String subjcode = rs.getString("subjcode");
                String subjdesc = rs.getString("subjdescription");
                String subjsched = rs.getString("subjschedule");
                String subjunit = rs.getString("subjunit");

                System.out.println("Fetched: " + subjid + ", " + subjcode + ", " + subjdesc + ", " + subjsched + ", " + subjunit);

                tblmodel.addRow(new Object[]{subjid, subjcode, subjdesc, subjsched, subjunit});
            }

            if (!hasResults) {
                JOptionPane.showMessageDialog(this, "No subjects assigned to teacher ID: " + teachID, "No Assignments", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Invalid teacher ID format.", "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error showing assigned subjects: " + ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }

    }
    private void TeachersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TeachersMouseClicked
        int selectedRow = Teachers.getSelectedRow();
        DefaultTableModel tblmodel = (DefaultTableModel) Teachers.getModel();

        teachid.setText(tblmodel.getValueAt(selectedRow, 0).toString());
        teachname.setText(tblmodel.getValueAt(selectedRow, 1).toString());
        teachaddress.setText(tblmodel.getValueAt(selectedRow, 2).toString());
        teachcontact.setText(tblmodel.getValueAt(selectedRow, 3).toString());
        teachemail.setText(tblmodel.getValueAt(selectedRow, 4).toString());
        teachdept.setText(tblmodel.getValueAt(selectedRow, 5).toString());
        
        ShowAssignRec();
    }//GEN-LAST:event_TeachersMouseClicked

    private void teachcontactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teachcontactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teachcontactActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        teach.SaveRecord(Integer.parseInt(teachid.getText()), teachname.getText(), teachaddress.getText(), teachcontact.getText(),teachemail.getText(), teachdept.getText());
        showRecords();
        clearFields();
        setNextTeacherID();
        
        
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        teach.DeleteRecord(Integer.parseInt(teachid.getText()));
        showRecords();
        clearFields();   // TODO add your handling code here:
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        teach.UpdateRecord(Integer.parseInt(teachid.getText()), teachname.getText(), teachaddress.getText(), teachcontact.getText(),teachemail.getText(), teachdept.getText());
        showRecords();
        clearFields();
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        DefaultTableModel tblmodel = (DefaultTableModel)Teachers.getModel();
        tblmodel.setRowCount(0);
        ColesEnrollmentSystem a = new ColesEnrollmentSystem();
        a.DBConnect();

        try {
            String query = "SELECT * FROM TeachersTable;";
            a.rs = a.st.executeQuery(query);

            while (a.rs.next()) {
                String teachid = a.rs.getString("teachid");
                String teachname = a.rs.getString("teachname");
                String teachaddress = a.rs.getString("teachaddress");
                String teachcontact = a.rs.getString("teachcontact");
                String teachemail = a.rs.getString("teachemail");
                String teachdept = a.rs.getString("teachdept");
                tblmodel.addRow(new Object[]{teachid, teachname, teachaddress, teachcontact, teachemail, teachdept});
            }
        } catch (Exception ex) {
            System.out.println(ex);
        }       
    }//GEN-LAST:event_formWindowOpened

    private void teachidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teachidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teachidActionPerformed

    private void teachnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teachnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teachnameActionPerformed

    private void StudentsmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentsmenuActionPerformed
        StudentsForm a = new StudentsForm();
        a.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_StudentsmenuActionPerformed

    private void SubjectsmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubjectsmenuActionPerformed
        SubjectsForm a = new SubjectsForm();
        a.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_SubjectsmenuActionPerformed

    private void assignbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignbuttonActionPerformed
        if (teachid.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select a teacher first.", "No Teacher Selected", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (subjectsFormInstance == null) {
            JOptionPane.showMessageDialog(this, "Please open the Subjects form first.", "Subjects Form Not Open", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String selectedSubjID = subjectsFormInstance.getSelectedSubjectID();
        if (selectedSubjID == null || selectedSubjID.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select a subject in the Subjects form first.", "No Subject Selected", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            int teacherID = Integer.parseInt(teachid.getText());
            int subjectID = Integer.parseInt(selectedSubjID);

            ColesEnrollmentSystem conn = new ColesEnrollmentSystem();
            conn.DBConnect();

            String checkQuery = "SELECT t.teachname FROM TeachersTable t "
                    + "INNER JOIN Assign a ON a.tid = t.teachid "
                    + "WHERE a.subid = ?";
            
            PreparedStatement ps = conn.con.prepareStatement(checkQuery);
            ps.setInt(1, subjectID);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                //String assignedTeacher = rs.getString("teachname");
                JOptionPane.showMessageDialog(this,
                        "Subject already assigned to: " + teacherID,
                        "Assignment Blocked",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }

            String confirmMessage = "Assign Teacher ID: " + teacherID + " to Subject ID: " + subjectID;
            int choice = JOptionPane.showConfirmDialog(this, confirmMessage, "Confirm Assignment", JOptionPane.OK_CANCEL_OPTION);

            if (choice == JOptionPane.OK_OPTION) {
                assignHandler.setsubjid(subjectID);
                String result = assignHandler.AssignSubj(teacherID);

                if (result.contains("successfully")) {
                    JOptionPane.showMessageDialog(this, "Teacher: " + teacherID + " assigned to " + subjectID + ".", "Assignment Successful", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, result, "Assignment Failed", JOptionPane.ERROR_MESSAGE);
                }

                ShowAssignRec();
                subjectsFormInstance.ShowClassList(); 
            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Invalid teacher or subject ID.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error during assignment: " + ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_assignbuttonActionPerformed

    private void deletesubjbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletesubjbuttonActionPerformed
        int selectedRow = assigntable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a subject to remove.", "No Subject Selected", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String teacherText = teachid.getText();
        if (teacherText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select a teacher first.", "No Teacher Selected", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            int teacherID = Integer.parseInt(teacherText);
            int subjectID = Integer.parseInt(assigntable.getValueAt(selectedRow, 0).toString());

            ColesEnrollmentSystem conn = new ColesEnrollmentSystem();
            conn.DBConnect();

            String query = "SELECT * FROM Assign WHERE tid = ? AND subid = ?";
            PreparedStatement ps = conn.con.prepareStatement(query);
            ps.setInt(1, teacherID);
            ps.setInt(2, subjectID);
            ResultSet rs = ps.executeQuery();

            if (!rs.next()) {
                JOptionPane.showMessageDialog(this, "No matching assignment found for deletion.", "Not Found", JOptionPane.WARNING_MESSAGE);
                return;
            }

            String confirm = "Delete Subject: " + subjectID + " assigned by Teacher: " + teacherID;
            int confirmChoice = JOptionPane.showConfirmDialog(this, confirm, "Confirm Delete Assignment", JOptionPane.OK_CANCEL_OPTION);

            if (confirmChoice == JOptionPane.OK_OPTION) {
                assignHandler.setsubjid(subjectID);
                String result = assignHandler.DeleteSubj(teacherID);

                if (result.contains("successfully")) {
                    JOptionPane.showMessageDialog(this, "Teacher: " + teacherID + " no longer assigned to Subject: " + subjectID, "Assignment Removed", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, result, "Deletion Failed", JOptionPane.ERROR_MESSAGE);
                }

                ShowAssignRec();

                if (subjectsFormInstance != null) {
                    subjectsFormInstance.showRecords();
                }
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid teacher or subject ID.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error during deletion: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_deletesubjbuttonActionPerformed
    private void setNextTeacherID() {
        try {
            ColesEnrollmentSystem conn = new ColesEnrollmentSystem();
            conn.DBConnect();

            String query = "SELECT MAX(teachid) FROM TeachersTable"; 
            PreparedStatement ps = conn.con.prepareStatement(query);
            ResultSet rs = ps.executeQuery();

            int nextID = 3001;
            if (rs.next()) {
                int maxID = rs.getInt(1); 
                if (!rs.wasNull() && maxID >= 3001) {
                    nextID = maxID + 1;
                }
            }

            teachid.setText(String.valueOf(nextID));

            rs.close();
            ps.close();
            conn.con.close();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error generating next Teacher ID: " + ex.getMessage(), "ID Generation Error", JOptionPane.ERROR_MESSAGE);
            teachid.setText("3001");
        }
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeachersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeachersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeachersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeachersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeachersForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton SaveButton;
    private javax.swing.JMenuItem Studentsmenu;
    private javax.swing.JMenuItem Subjectsmenu;
    private javax.swing.JTable Teachers;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JButton assignbutton;
    private javax.swing.JTable assigntable;
    private javax.swing.JButton deletesubjbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField teachaddress;
    private javax.swing.JTextField teachcontact;
    private javax.swing.JTextField teachdept;
    private javax.swing.JTextField teachemail;
    private javax.swing.JTextField teachid;
    private javax.swing.JTextField teachname;
    // End of variables declaration//GEN-END:variables
}
